# This is only an EXAMPLE of deploying JetAuth in Kubernetes.
# Please modify this file according to your requirements.
apiVersion: v1
kind: Service
metadata:
  # EDIT IT: if you don't want to run JetAuth in default namespace, please modify this field
  #namespace: jetauth
  name: jetauth-svc
  labels:
    app: jetauth
spec:
  # EDIT IT: if you don't want to run JetAuth in default namespace, please modify this field
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: jetauth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # EDIT IT: if you don't want to run JetAuth in default namespace, please modify this field
  #namespace: jetauth
  name: jetauth-deployment
  labels:
    app: jetauth
spec:
  # EDIT IT: if you don't use redis, JetAuth should not have multiple replicas
  replicas: 1
  selector:
    matchLabels:
      app: jetauth
  template:
    metadata:
      labels:
        app: jetauth
    spec:
      containers:
        - name: jetauth-container
          # EDIT IT: replace with your own image registry / tag
          image: your-registry/jetauth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            # the mounted directory path in THE CONTAINER
            - mountPath: /conf
              name: conf
          env:
            - name: RUNNING_IN_DOCKER
              value: "true"
      # if you want to deploy this in real prod env, consider the config map
      volumes:
        - name: conf
          hostPath:
            # EDIT IT: the mounted directory path in THE HOST
            path: /conf
