// Copyright 2026 The JetAuth Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0

package object

import (
	"fmt"
	"strings"
	"sync"

	"github.com/beego/beego/v2/core/logs"
	"github.com/casbin/casbin/v3"
	"github.com/casbin/casbin/v3/model"
	xormadapter "github.com/deluxebear/casdoor/adapters/xormadapter"
	"github.com/deluxebear/casdoor/conf"
	"github.com/deluxebear/casdoor/util"
	"github.com/xorm-io/core"
)

// Per-app mutex ensures atomic incremental sync (no concurrent modification
// of the same app's policies).
var bizSyncMu sync.Map // key: "owner/appName" → *sync.Mutex

func getBizSyncLock(owner, appName string) *sync.Mutex {
	key := util.GetId(owner, appName)
	val, _ := bizSyncMu.LoadOrStore(key, &sync.Mutex{})
	return val.(*sync.Mutex)
}

// ── Policy computation helpers ──

// computeRoleGPolicies returns the g (grouping) policies generated by a single role.
// Returns nil if the role is disabled.
//
// Direct members (users, groups) plus every transitive ancestor's members are
// emitted as flat g-rules targeting THIS role's name. Flattening keeps Casbin's
// enforce path O(1) per check instead of walking an inheritance graph on each
// call. The tradeoff — more g-rules in storage — is cheap given policy sizes.
//
// "userset" subjects are skipped in phase 1 (ReBAC resolution isn't wired yet).
func computeRoleGPolicies(role *BizRole) ([][]string, error) {
	if role == nil || !role.IsEnabled {
		return nil, nil
	}

	var gp [][]string

	// Direct members
	members, err := ListBizRoleMembers(role.Id)
	if err != nil {
		return nil, err
	}
	for _, m := range members {
		if m.SubjectType == BizRoleSubjectUserset {
			continue
		}
		gp = append(gp, []string{m.SubjectId, role.Name})
	}

	// Inherited ancestors' members contribute to THIS role as well. This
	// flattening mirrors what Casbin's RoleManager would resolve at enforce
	// time, but precomputed at sync time so runtime stays fast.
	ancestorIds, err := ExpandRoleAncestors(role.Id)
	if err != nil {
		return nil, err
	}
	for _, ancId := range ancestorIds {
		ancMembers, err := ListBizRoleMembers(ancId)
		if err != nil {
			return nil, err
		}
		for _, m := range ancMembers {
			if m.SubjectType == BizRoleSubjectUserset {
				continue
			}
			gp = append(gp, []string{m.SubjectId, role.Name})
		}
	}

	return gp, nil
}

// computePermPPolicies returns the p policies generated by a single permission.
// Returns nil if the permission is disabled or not approved.
//
// Subjects come from the biz_permission_grantee relational table. user/group/
// role grantees are flattened into the p rule's `sub` slot identically — the
// Casbin g-rules emitted by computeRoleGPolicies translate user→role lookups.
// "userset" grantees are skipped in phase 1.
func computePermPPolicies(perm *BizPermission, hasEft bool) ([][]string, error) {
	if perm == nil || !perm.IsEnabled || perm.State != StateApproved {
		return nil, nil
	}

	grantees, err := ListBizPermissionGrantees(perm.Id)
	if err != nil {
		return nil, err
	}

	subs := make([]string, 0, len(grantees))
	for _, g := range grantees {
		if g.SubjectType == BizPermGranteeUserset {
			continue
		}
		subs = append(subs, g.SubjectId)
	}

	var pp [][]string
	for _, sub := range subs {
		for _, res := range perm.Resources {
			for _, act := range perm.Actions {
				if hasEft {
					eft := casbinEftAllow
					if perm.Effect == EffectDeny {
						eft = casbinEftDeny
					}
					pp = append(pp, []string{sub, res, act, eft})
				} else {
					pp = append(pp, []string{sub, res, act})
				}
			}
		}
	}
	return pp, nil
}

// detectHasEft checks whether the enforcer model includes an eft field in p.
func detectHasEft(e *casbin.Enforcer) bool {
	if pDef, ok := e.GetModel()["p"]["p"]; ok {
		for _, tok := range pDef.Tokens {
			if tok == "p_eft" {
				return true
			}
		}
	}
	return false
}

// validateBizPermissionModel rejects models whose policy shape the engine
// cannot populate from BizPermission. BizPermission carries Users/Roles,
// Resources, Actions, and Effect — these map to a 3- or 4-column policy.
// Higher-arity models (e.g. `p = sub, dom, obj, act`) have fields we have
// no source data for, and silently emitting wrong-arity rules either errors
// inside Casbin or persists a broken policy table that denies all enforce
// calls. Fail loud at sync time instead.
func validateBizPermissionModel(e *casbin.Enforcer) error {
	pDef, ok := e.GetModel()["p"]["p"]
	if !ok {
		return fmt.Errorf("model missing [policy_definition] p")
	}
	n := len(pDef.Tokens)
	switch n {
	case 3:
		return nil
	case 4:
		for _, tok := range pDef.Tokens {
			if tok == "p_eft" {
				return nil
			}
		}
	}
	return fmt.Errorf("biz-permission engine supports policy shape [sub, obj, act] or [sub, obj, act, eft]; got %d fields %v", n, pDef.Tokens)
}

// bumpBizAppConfigUpdatedTime refreshes BizAppConfig.UpdatedTime for the given
// app so SDKs polling /biz-get-policies see a new `version` after a role or
// permission change. Returns the new timestamp string so callers can reuse it
// in cache writes without re-reading the row.
func bumpBizAppConfigUpdatedTime(owner, appName string) string {
	now := util.GetCurrentTime()
	if _, err := ormer.Engine.ID(core.PK{owner, appName}).Cols("updated_time").Update(&BizAppConfig{UpdatedTime: now}); err != nil {
		logs.Warning("failed to bump BizAppConfig.UpdatedTime for %s/%s: %v", owner, appName, err)
	}
	return now
}

// detectHasRoleDef checks whether the model has [role_definition].
// Uses the shared HasRoleDefinition helper from model.go.
func detectHasRoleDef(e *casbin.Enforcer) bool {
	return HasRoleDefinition(e.GetModel())
}

// ── In-memory enforcer builder ──

// buildEnforcerInMemory creates a new adapter-less enforcer with the given policies.
// This is used for atomic enforcer replacement in the cache.
func buildEnforcerInMemory(modelText string, policies, groupingPolicies [][]string) (*casbin.Enforcer, error) {
	m, err := model.NewModelFromString(modelText)
	if err != nil {
		return nil, err
	}
	e, err := casbin.NewEnforcer(m)
	if err != nil {
		return nil, err
	}
	if len(policies) > 0 {
		if _, err := e.AddPolicies(policies); err != nil {
			return nil, err
		}
	}
	if len(groupingPolicies) > 0 {
		if _, err := e.AddGroupingPolicies(groupingPolicies); err != nil {
			return nil, err
		}
	}
	return e, nil
}

// ── Standalone DB adapter ──

// buildPolicyAdapter creates a standalone xorm adapter for direct DB writes.
func buildPolicyAdapter(policyTable string) (*xormadapter.Adapter, error) {
	prefix := conf.GetConfigString("tableNamePrefix")
	return xormadapter.NewAdapterByEngineWithTableName(ormer.Engine, policyTable, prefix)
}

// ── Policy diff helpers ──

// policyKey returns a string key for dedup/comparison of a policy row.
func policyKey(p []string) string {
	return strings.Join(p, "\x00")
}

// diffPolicies computes added and removed policies between old and new sets.
func diffPolicies(oldPolicies, newPolicies [][]string) (added, removed [][]string) {
	oldSet := make(map[string]bool, len(oldPolicies))
	for _, p := range oldPolicies {
		oldSet[policyKey(p)] = true
	}
	newSet := make(map[string]bool, len(newPolicies))
	for _, p := range newPolicies {
		newSet[policyKey(p)] = true
	}
	for _, p := range newPolicies {
		if !oldSet[policyKey(p)] {
			added = append(added, p)
		}
	}
	for _, p := range oldPolicies {
		if !newSet[policyKey(p)] {
			removed = append(removed, p)
		}
	}
	return
}

// applyDiff removes and adds policies to a slice, returning the result.
func applyDiff(current [][]string, toRemove, toAdd [][]string) [][]string {
	if len(toRemove) == 0 && len(toAdd) == 0 {
		return current
	}
	removeSet := make(map[string]bool, len(toRemove))
	for _, p := range toRemove {
		removeSet[policyKey(p)] = true
	}
	result := make([][]string, 0, len(current)+len(toAdd))
	for _, p := range current {
		if !removeSet[policyKey(p)] {
			result = append(result, p)
		}
	}
	result = append(result, toAdd...)
	return result
}

// ── Sync trigger wrappers (relational model) ──
//
// After moving members/grantees/inheritance into their own tables, the old
// "diff two struct snapshots" approach no longer applies — the struct no
// longer carries the subject arrays to diff. Each mutation instead identifies
// the affected role (or permission) by id, and we rebuild Casbin policies for
// every app whose enforcer that role/permission participates in.
//
// Fan-out is bounded: app-scope role → one app; org-scope role → apps that
// grant that role via biz_permission_grantee (indexed lookup). Each rebuild
// is O(policies_in_app) but runs in a goroutine so request latency is
// unaffected. Synchronous re-sync is reserved for the permission-centric
// `syncAffectedAppsByPermissionId` path that already exists.

// SyncAfterRoleUpdated is called after a BizRole row's metadata (name,
// enabled, scope, …) has been updated. Fans out to every app whose policies
// reference the role.
func SyncAfterRoleUpdated(org, appName string, roleId int64) {
	syncAffectedApps(org, appName, roleId)
}

// SyncAfterRoleDeleted is called after a BizRole (and its members/inheritance
// edges) have been removed from the DB.
func SyncAfterRoleDeleted(org, appName string, roleId int64) {
	syncAffectedApps(org, appName, roleId)
}

// SyncAfterRoleMemberAdded is called after biz_role_member gains a row.
func SyncAfterRoleMemberAdded(org, appName string, roleId int64) {
	syncAffectedApps(org, appName, roleId)
}

// SyncAfterRoleMemberRemoved is called after biz_role_member loses a row.
func SyncAfterRoleMemberRemoved(org, appName string, roleId int64) {
	syncAffectedApps(org, appName, roleId)
}

// SyncAfterInheritanceChanged is called after biz_role_inheritance gains or
// loses an edge. The change affects policies derived from childRoleId (the
// role whose ancestors just changed).
func SyncAfterInheritanceChanged(org, appName string, childRoleId int64) {
	syncAffectedApps(org, appName, childRoleId)
}

// syncAffectedApps dispatches a rebuild for every app whose Casbin enforcer
// depends on the given role.
//   - App-scope role: just the owning app.
//   - Org-scope role: every app that has a BizPermissionGrantee row of
//     type='role' pointing at this role's name (indexed lookup).
//
// Rebuilds are fire-and-forget goroutines so mutation endpoints don't block.
func syncAffectedApps(org, appName string, roleId int64) {
	role, err := getBizRoleById(roleId)
	if err != nil || role == nil {
		// Role already gone (delete path) or a DB error. Best we can do for
		// delete is sync the app we were told about; cross-app fan-out needs
		// the role name which we no longer have, so callers that care about
		// org-scope delete fan-out should pass appName == "" after a prior
		// snapshot — today, that's not a code path.
		if appName != "" {
			go func(o, a string) { _, _ = SyncAppPolicies(o, a) }(org, appName)
		}
		return
	}

	if role.ScopeKind == BizRoleScopeApp {
		go func(o, a string) { _, _ = SyncAppPolicies(o, a) }(org, role.AppName)
		return
	}

	// Org-scope: fan out to every app that references this role name.
	affected, err := findAppsReferencingRoleName(org, role.Name)
	if err != nil {
		logs.Warning("findAppsReferencingRoleName(%s,%s) failed: %v", org, role.Name, err)
		return
	}
	for _, app := range affected {
		go func(o, a string) { _, _ = SyncAppPolicies(o, a) }(org, app)
	}
}

// findAppsReferencingRoleName returns the distinct app names whose permissions
// grant this role. Indexed lookup via biz_permission_grantee
// (subject_type='role', subject_id=name) → biz_permission.app_name.
func findAppsReferencingRoleName(org, roleName string) ([]string, error) {
	perms := []*BizPermission{}
	err := ormer.Engine.
		Join("INNER", "biz_permission_grantee",
			"biz_permission.id = biz_permission_grantee.permission_id").
		Where("biz_permission.owner = ? AND biz_permission_grantee.subject_type = ? AND biz_permission_grantee.subject_id = ?",
			org, BizPermGranteeRole, roleName).
		Find(&perms)
	if err != nil {
		return nil, err
	}
	appSet := map[string]bool{}
	for _, p := range perms {
		appSet[p.AppName] = true
	}
	out := make([]string, 0, len(appSet))
	for app := range appSet {
		out = append(out, app)
	}
	return out, nil
}
