// Copyright 2026 The JetAuth Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0

package object

import (
	"strings"
	"sync"

	"github.com/beego/beego/v2/core/logs"
	"github.com/casbin/casbin/v3"
	"github.com/casbin/casbin/v3/model"
	xormadapter "github.com/deluxebear/casdoor/adapters/xormadapter"
	"github.com/deluxebear/casdoor/conf"
	"github.com/deluxebear/casdoor/util"
)

// Per-app mutex ensures atomic incremental sync (no concurrent modification
// of the same app's policies).
var bizSyncMu sync.Map // key: "owner/appName" → *sync.Mutex

func getBizSyncLock(owner, appName string) *sync.Mutex {
	key := util.GetId(owner, appName)
	val, _ := bizSyncMu.LoadOrStore(key, &sync.Mutex{})
	return val.(*sync.Mutex)
}

// ── Policy computation helpers ──

// computeRoleGPolicies returns the g (grouping) policies generated by a single role.
// Returns nil if the role is disabled.
func computeRoleGPolicies(role *BizRole) [][]string {
	if role == nil || !role.IsEnabled {
		return nil
	}
	var gp [][]string
	for _, u := range role.Users {
		gp = append(gp, []string{u, role.Name})
	}
	for _, sr := range role.Roles {
		gp = append(gp, []string{sr, role.Name})
	}
	return gp
}

// computePermPPolicies returns the p policies generated by a single permission.
// Returns nil if the permission is disabled or not approved.
func computePermPPolicies(perm *BizPermission, hasEft bool) [][]string {
	if perm == nil || !perm.IsEnabled || perm.State != StateApproved {
		return nil
	}
	subs := make([]string, 0, len(perm.Users)+len(perm.Roles))
	subs = append(subs, perm.Users...)
	subs = append(subs, perm.Roles...)

	var pp [][]string
	for _, sub := range subs {
		for _, res := range perm.Resources {
			for _, act := range perm.Actions {
				if hasEft {
					eft := casbinEftAllow
					if perm.Effect == EffectDeny {
						eft = casbinEftDeny
					}
					pp = append(pp, []string{sub, res, act, eft})
				} else {
					pp = append(pp, []string{sub, res, act})
				}
			}
		}
	}
	return pp
}

// detectHasEft checks whether the enforcer model includes an eft field in p.
func detectHasEft(e *casbin.Enforcer) bool {
	if pDef, ok := e.GetModel()["p"]["p"]; ok {
		for _, tok := range pDef.Tokens {
			if tok == "p_eft" {
				return true
			}
		}
	}
	return false
}

// detectHasRoleDef checks whether the model has [role_definition].
// Uses the shared HasRoleDefinition helper from model.go.
func detectHasRoleDef(e *casbin.Enforcer) bool {
	return HasRoleDefinition(e.GetModel())
}

// ── In-memory enforcer builder ──

// buildEnforcerInMemory creates a new adapter-less enforcer with the given policies.
// This is used for atomic enforcer replacement in the cache.
func buildEnforcerInMemory(modelText string, policies, groupingPolicies [][]string) (*casbin.Enforcer, error) {
	m, err := model.NewModelFromString(modelText)
	if err != nil {
		return nil, err
	}
	e, err := casbin.NewEnforcer(m)
	if err != nil {
		return nil, err
	}
	if len(policies) > 0 {
		if _, err := e.AddPolicies(policies); err != nil {
			return nil, err
		}
	}
	if len(groupingPolicies) > 0 {
		if _, err := e.AddGroupingPolicies(groupingPolicies); err != nil {
			return nil, err
		}
	}
	return e, nil
}

// ── Standalone DB adapter ──

// buildPolicyAdapter creates a standalone xorm adapter for direct DB writes.
func buildPolicyAdapter(policyTable string) (*xormadapter.Adapter, error) {
	prefix := conf.GetConfigString("tableNamePrefix")
	return xormadapter.NewAdapterByEngineWithTableName(ormer.Engine, policyTable, prefix)
}

// ── Policy diff helpers ──

// policyKey returns a string key for dedup/comparison of a policy row.
func policyKey(p []string) string {
	return strings.Join(p, "\x00")
}

// diffPolicies computes added and removed policies between old and new sets.
func diffPolicies(oldPolicies, newPolicies [][]string) (added, removed [][]string) {
	oldSet := make(map[string]bool, len(oldPolicies))
	for _, p := range oldPolicies {
		oldSet[policyKey(p)] = true
	}
	newSet := make(map[string]bool, len(newPolicies))
	for _, p := range newPolicies {
		newSet[policyKey(p)] = true
	}
	for _, p := range newPolicies {
		if !oldSet[policyKey(p)] {
			added = append(added, p)
		}
	}
	for _, p := range oldPolicies {
		if !newSet[policyKey(p)] {
			removed = append(removed, p)
		}
	}
	return
}

// applyDiff removes and adds policies to a slice, returning the result.
func applyDiff(current [][]string, toRemove, toAdd [][]string) [][]string {
	if len(toRemove) == 0 && len(toAdd) == 0 {
		return current
	}
	removeSet := make(map[string]bool, len(toRemove))
	for _, p := range toRemove {
		removeSet[policyKey(p)] = true
	}
	result := make([][]string, 0, len(current)+len(toAdd))
	for _, p := range current {
		if !removeSet[policyKey(p)] {
			result = append(result, p)
		}
	}
	result = append(result, toAdd...)
	return result
}

// ── Incremental sync: roles ──

// SyncRoleIncremental handles incremental policy sync when a role changes.
//   - Add:    oldRole=nil, newRole=role
//   - Delete: oldRole=role, newRole=nil
//   - Update: oldRole=before, newRole=after
//
// Falls back to full rebuild if no cached enforcer or on error.
func SyncRoleIncremental(owner, appName string, oldRole, newRole *BizRole) {
	mu := getBizSyncLock(owner, appName)
	mu.Lock()
	defer mu.Unlock()

	key := util.GetId(owner, appName)
	val, ok := bizEnforcerCache.Load(key)
	if !ok {
		syncBizPolicies(owner, appName)
		return
	}
	e := val.(*casbin.Enforcer)

	config, err := getBizAppConfigOrError(owner, appName)
	if err != nil {
		logs.Warning("incremental role sync: config error, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	// No role_definition → no g policies to sync
	if !detectHasRoleDef(e) {
		return
	}

	oldGP := computeRoleGPolicies(oldRole)
	newGP := computeRoleGPolicies(newRole)
	added, removed := diffPolicies(oldGP, newGP)

	if len(added) == 0 && len(removed) == 0 {
		return // no change
	}

	// Extract current policies, apply diff to g policies
	currentP, currentG := extractPolicies(e)
	updatedG := applyDiff(currentG, removed, added)

	// Build new enforcer with updated policies (atomic replacement)
	newE, err := buildEnforcerInMemory(config.ModelText, currentP, updatedG)
	if err != nil {
		logs.Warning("incremental role sync: enforcer build failed, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	// Persist delta to DB policy table
	if adapter, err := buildPolicyAdapter(config.PolicyTable); err == nil {
		if len(removed) > 0 {
			if err := adapter.RemovePolicies("g", "g", removed); err != nil {
				logs.Warning("incremental role sync: DB remove failed, falling back: %v", err)
				syncBizPolicies(owner, appName)
				return
			}
		}
		if len(added) > 0 {
			if err := adapter.AddPolicies("g", "g", added); err != nil {
				logs.Warning("incremental role sync: DB add failed, falling back: %v", err)
				syncBizPolicies(owner, appName)
				return
			}
		}
	} else {
		logs.Warning("incremental role sync: adapter creation failed, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	// Atomically swap enforcer in cache + update Redis
	StoreBizEnforcerCache(owner, appName, newE)
	bizPolicyCacheSet(owner, appName, &BizPolicyCacheData{
		ModelText:        config.ModelText,
		Policies:         currentP,
		GroupingPolicies: updatedG,
		PolicyTable:      config.PolicyTable,
		UpdatedTime:      config.UpdatedTime,
	})

	logs.Info("incremental role sync: %s/%s role=%s added=%d removed=%d",
		owner, appName, roleName(oldRole, newRole), len(added), len(removed))
}

// ── Incremental sync: permissions ──

// SyncPermissionIncremental handles incremental policy sync when a permission changes.
//   - Add:    oldPerm=nil, newPerm=perm
//   - Delete: oldPerm=perm, newPerm=nil
//   - Update: oldPerm=before, newPerm=after
func SyncPermissionIncremental(owner, appName string, oldPerm, newPerm *BizPermission) {
	mu := getBizSyncLock(owner, appName)
	mu.Lock()
	defer mu.Unlock()

	key := util.GetId(owner, appName)
	val, ok := bizEnforcerCache.Load(key)
	if !ok {
		syncBizPolicies(owner, appName)
		return
	}
	e := val.(*casbin.Enforcer)

	config, err := getBizAppConfigOrError(owner, appName)
	if err != nil {
		logs.Warning("incremental perm sync: config error, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	hasEft := detectHasEft(e)
	oldPP := computePermPPolicies(oldPerm, hasEft)
	newPP := computePermPPolicies(newPerm, hasEft)
	added, removed := diffPolicies(oldPP, newPP)

	if len(added) == 0 && len(removed) == 0 {
		return // no change
	}

	// Extract current policies, apply diff to p policies
	currentP, currentG := extractPolicies(e)
	updatedP := applyDiff(currentP, removed, added)

	// Build new enforcer
	newE, err := buildEnforcerInMemory(config.ModelText, updatedP, currentG)
	if err != nil {
		logs.Warning("incremental perm sync: enforcer build failed, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	// Persist delta to DB
	if adapter, err := buildPolicyAdapter(config.PolicyTable); err == nil {
		if len(removed) > 0 {
			if err := adapter.RemovePolicies("p", "p", removed); err != nil {
				logs.Warning("incremental perm sync: DB remove failed, falling back: %v", err)
				syncBizPolicies(owner, appName)
				return
			}
		}
		if len(added) > 0 {
			if err := adapter.AddPolicies("p", "p", added); err != nil {
				logs.Warning("incremental perm sync: DB add failed, falling back: %v", err)
				syncBizPolicies(owner, appName)
				return
			}
		}
	} else {
		logs.Warning("incremental perm sync: adapter creation failed, falling back: %v", err)
		syncBizPolicies(owner, appName)
		return
	}

	// Update caches
	StoreBizEnforcerCache(owner, appName, newE)
	bizPolicyCacheSet(owner, appName, &BizPolicyCacheData{
		ModelText:        config.ModelText,
		Policies:         updatedP,
		GroupingPolicies: currentG,
		PolicyTable:      config.PolicyTable,
		UpdatedTime:      config.UpdatedTime,
	})

	logs.Info("incremental perm sync: %s/%s perm=%s added=%d removed=%d",
		owner, appName, permName(oldPerm, newPerm), len(added), len(removed))
}

// ── Helpers ──

func roleName(oldRole, newRole *BizRole) string {
	if newRole != nil {
		return newRole.Name
	}
	if oldRole != nil {
		return oldRole.Name
	}
	return "?"
}

func permName(oldPerm, newPerm *BizPermission) string {
	if newPerm != nil {
		return newPerm.Name
	}
	if oldPerm != nil {
		return oldPerm.Name
	}
	return "?"
}

// ── Wrappers called by CRUD functions ──

// SyncAfterRoleAdd is called after a new role is inserted into DB.
func SyncAfterRoleAdd(role *BizRole) {
	SyncRoleIncremental(role.Owner, role.AppName, nil, role)
}

// SyncAfterRoleUpdate is called after a role is updated in DB.
// oldRole is the state before update (read from DB before the update).
func SyncAfterRoleUpdate(oldRole, newRole *BizRole) {
	SyncRoleIncremental(oldRole.Owner, oldRole.AppName, oldRole, newRole)
}

// SyncAfterRoleDelete is called after a role is deleted from DB.
func SyncAfterRoleDelete(role *BizRole) {
	SyncRoleIncremental(role.Owner, role.AppName, role, nil)
}

// SyncAfterPermissionAdd is called after a new permission is inserted into DB.
func SyncAfterPermissionAdd(perm *BizPermission) {
	SyncPermissionIncremental(perm.Owner, perm.AppName, nil, perm)
}

// SyncAfterPermissionUpdate is called after a permission is updated in DB.
func SyncAfterPermissionUpdate(oldPerm, newPerm *BizPermission) {
	SyncPermissionIncremental(oldPerm.Owner, oldPerm.AppName, oldPerm, newPerm)
}

// SyncAfterPermissionDelete is called after a permission is deleted from DB.
func SyncAfterPermissionDelete(perm *BizPermission) {
	SyncPermissionIncremental(perm.Owner, perm.AppName, perm, nil)
}

